### ISSUE TITLE
Snap package ready and working

### ISSUE THREAD

**Issue by soumyaDghosh** [jkotra/unlockr#14]
Hii, I have created a snap package for your app. Would you like to have it?

**Comment by jkotra** [comment]
Thanks for the effort @soumyaDghosh.

However, I cannot add snap packaging to the repository at this point of time due to additional maintenance responsibility it brings.

as per the [license](https://github.com/jkotra/unlockr/blob/main/LICENSE), you are free to distribute the snaps wherever you like as long as you provide credits.
